### ISSUE TITLE
Activation email is not sent upon account creation

### ISSUE THREAD

**Issue by thedarkspy** [cibr-qcri/kansa#175]
**Describe the bug**
Create an account on the website and wait for the activation email, you get an error saying "Could not send activation email". 

**To Reproduce**
1. Go to the website
2. Create account
3. No email is received

**Expected behavior**
An activation email should be sent to your email.

**Comment by boshmaf** [comment]
After debugging it turns out the wrong password was based as an env variables in the API container. Digging deeper, it turns out there was a manual deployment of Jenkins where secrets are passed as env variables (so you won't add them through the UI). That manual deployment had old password because it was copied from an old history entry. We need a more secure way to bootstrap passwords that doesn't depend on plain history (like export an encrypted Jenkins secret file and import it on deployment). See cibr-qcri/jenkins#20
