### ISSUE TITLE
Database connection unexpectedly drops

### ISSUE THREAD

**Issue by thedarkspy** [cibr-qcri/kansa#217]
**Describe the bug**
Database connection unexpectedly drops causing the server to return 500 error

**To Reproduce**
1. Not sure how to reproduce but it seems that it happens when the server is overwhelmed with requests.

**Expected behavior**
The server should always return 200 or the proper error.

**Additional**
<img width="801" alt="Screenshot 2023-01-04 at 11 53 56 AM" src="https://user-images.githubusercontent.com/10672009/210518484-7a506a67-8cad-40c9-aa06-1f3475c9bdfa.png">

**Comment by sajithaliyanage** [comment]
The following things were observed during the debugging and mentioned actions were taken.
 
- Could not notice any error log on default Greenplum server logs related to this issue.
- 10.4.8.177 server was running at 100% capacity with data storage space issues. As an action, the infrastructure team was contacted and requested to manually migrate the datastore to a different space.
- Increased the database connection pool size of the Airflow database (Observed max_connections reached errors in tasks logs)
- Removed unwanted tables/indexes in order to have more free spaces in Greenplum PVC
- Restarted the Greenplum server
